version: '3'
services:
  datasette:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["datasette", "-h", "0.0.0.0", "--cors", "/mnt/datasette/databases"]
    ports:
      - "8001:8001"
    volumes:
      - ./plugins:/mnt/datasette/databases/plugins