version: '3'
services:
  datasette:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["datasette", "-h", "0.0.0.0", "--cors", "-i", "databases/darien.db", "-i", "databases/gorongosa.db", "--plugins-dir=databases/plugins", "--inspect-file=databases/inspect-data.json", "--setting", "sql_time_limit_ms", "60000",  "--setting", "max_returned_rows", "2000", "--setting", "hash_urls", "1"]
    ports:
      - "8001:8001"
    volumes:
      - ./plugins:/mnt/datasette/databases/plugins